In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train_data=pd.read_csv("newsgroups_train.csv")

In [3]:
test_data=pd.read_csv("newsgroups_test.csv")

In [4]:
train_data.head()

text  target       category
0  From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1  From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2  From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3  From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4  From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space

In [9]:
from sklearn.datasets import fetch_20newsgroups
cats=['alt.atheism','comp.graphics','sci.space']


In [11]:
train=fetch_20newsgroups(subset='train',categories=cats,shuffle=True,random_state=42)

In [13]:


test=fetch_20newsgroups(subset='test',categories=cats,shuffle=True,random_state=42)

In [15]:
train.target_names

['alt.atheism', 'comp.graphics', 'sci.space']

In [17]:
len(train.data)

1657

In [19]:
train.data[5]

'From: dietz@cs.rochester.edu (Paul Dietz)\nSubject: Commercial mining activities on the moon\nOrganization: University of Rochester\nLines: 38\n\nIn article <1993Apr20.152819.28186@ke4zv.uucp> gary@ke4zv.UUCP (Gary Coffman) writes:\n\n > be the site of major commercial activity. As far as we know it has no\n > materials we can\'t get cheaper right here on Earth or from asteroids\n > and comets, aside from the semi-mythic He3 that *might* be useful in low\n > grade fusion reactors.\n\nI don\'t know what a "low grade" fusion reactor is, but the major\nproblem with 3He (aside from the difficulty in making any fusion\nreactor work) is that its concentration in lunar regolith is just so\nsmall -- on the order of 5 ppb or so, on average (more in some\nfractions, but still very small).  Massive amounts of regolith would\nhave to be processed.\n\nThis thread reminds me of Wingo\'s claims some time ago about the moon\nas a source of titanium for use on earth.  As I recall, Wingo wasn\'t\nconte

In [21]:
len(train.data)


1657

In [23]:
len(train.target)

1657

In [25]:
train.filenames

array(['/home/user/scikit_learn_data/20news_home/20news-bydate-train/sci.space/60869',
       '/home/user/scikit_learn_data/20news_home/20news-bydate-train/comp.graphics/38633',
       '/home/user/scikit_learn_data/20news_home/20news-bydate-train/alt.atheism/53534',
       ...,
       '/home/user/scikit_learn_data/20news_home/20news-bydate-train/sci.space/60915',
       '/home/user/scikit_learn_data/20news_home/20news-bydate-train/sci.space/60176',
       '/home/user/scikit_learn_data/20news_home/20news-bydate-train/sci.space/60929'],
      dtype='<U91')

In [27]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from os import XATTR_CREATE
from sklearn.naive_bayes import BernoulliNB
cv=CountVectorizer(max_features=1000)
train_count=cv.fit_transform(train.data)
b=BernoulliNB()
b.fit(train_count,train.target)
test_count=cv.transform(test.data)
y_pred=b.predict(test_count)

In [28]:
y_pred

array([2, 1, 1, ..., 0, 1, 2])

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(test.target,y_pred))

0.8284936479128857


In [33]:

from os import XATTR_CREATE
from sklearn.naive_bayes import BernoulliNB,MultinomialNB
tf=TfidfVectorizer(max_features=1000,stop_words='english')
train_count=tf.fit_transform(train.data)
m=MultinomialNB()
m.fit(train_count,train.target)
test_count=tf.transform(test.data)
y_p=m.predict(test_count)

In [35]:
y_p

array([2, 1, 1, ..., 0, 1, 2])

In [37]:
print(accuracy_score(test.target,y_pred))

0.8284936479128857


In [39]:
y_p.shape

(1102,)

In [45]:
print(confusion_matrix(test.target,y_pred))

[[260  51   8]
 [ 12 347  30]
 [ 12  76 306]]


In [ ]:
sns.